name: "Deploy SolarKit"
on:
  push:
    branches: ['main']
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: "ubuntu-latest"
    name: "Build"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - run: go version
    - run: |
      ls -lah
      go test -v ./..
  # deploy-nativeruntime:
  # deploy-tailscale:
  deploy-functions:
    runs-on: "ubuntu-latest"
    name: "Deploy to GCF"
    needs: ['build'] # TODO: pull build from step, re-use
    steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.8.0
      with:
        workload_identity_provider: 'projects/163317929648/locations/global/workloadIdentityPools/native-runtime-pool/providers/github-repository-provider'
        service_account: 'native-runtime-access@rubynerd-net.iam.gserviceaccount.com'
    - uses: google-github-actions/setup-gcloud@v2
    - name: 'Deploy the weather function'
      run: >
        gcloud --quiet
        functions deploy solarkit-weather
        --gen2
        --runtime=go121
        --region=europe-central2
        --source=.
        --entry-point=solarkit-weather
        --trigger-http
        --allow-unauthenticated
        --set-secrets='/etc/secrets/weatherkit-weather/latest=solarkit-weatherkit-development:latest'
